items:
  - name: classified
    fields:
      - name: title
        type: string
      - name: price
        type: number
      - name: estateType
        type: string
      - name: city
        type: string
      - name: postalCode
        type: string
      - name: transaction
        type: string
features:
  - name: price
    type: number
    scope: item
    field: item.price

  - name: estate_type
    type: string
    scope: item
    field: item.estateType
    encode: onehot
    values: [apartment, house, studio]

  - name: city
    type: string
    scope: item
    field: item.city
    encode: onehot
    values: [apartment, house, studio]
models:
  semantic:
    type: semantic
    encoder:
      type: bert
      model: metarank/all-MiniLM-L6-v2
      dim: 384
    itemFields:
      - title
      - estateType
      - city
api:
  analytics: false
